name: Sales Dashboard Server CI/CD

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: [self-hosted, test, main]

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          clean: "false"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Restart PM2 Service
        run: |
          npm run stop:pm2 || true
          npm run start:pm2
